Obligatorio2/Controllers/InicioSesionController.cs
using Biblioteca;
using Microsoft.AspNetCore.Mvc;

namespace Obligatorio2.Controllers
{
    public class InicioSesionController : Controller
    {
        public IActionResult Index()
        {
            string? us = HttpContext.Session.GetString("usuarioLogueado");
            if (us == null)
            {
                return View();
            }
            else
            {
                TempData["MensajeError"] = "Acceso Denegado";
                return RedirectToAction("Index", "Error");
            }
            
        }
        [HttpPost]
        public IActionResult Login(Usuario s)
        {
            
            try
            {                
                Usuario userLogueado = Sistema.ObtenerInstancia.IniciarSesion(s.Email, s.Contraseña);
                HttpContext.Session.SetString("usuarioLogueado", userLogueado.Email);
                HttpContext.Session.SetString("Rol", userLogueado.Rol);
                HttpContext.Session.SetInt32("Id", userLogueado.Id);

                return RedirectToAction("IdentificarRol");
            } catch (Exception ex)
            {
                TempData["MensajeError"] = ex.Message;
                return RedirectToAction("Index");
            }
        }


        public IActionResult IdentificarRol() 
        {            
            string? rol = HttpContext.Session.GetString("Rol");

                if (rol!= null && rol.Equals("Admin")) 
            {

             return RedirectToAction("Index", "Administrador");

            }else if (rol!= null && rol.Equals("Miembro"))
            {
                return RedirectToAction("Inicio", "Miembro");
            } else
            {
                return RedirectToAction("Index");
            }

        }

    }


  
}

Obligatorio2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Obligatorio2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Obligatorio2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Obligatorio2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (Context.Session.GetString("usuarioLogueado") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="Logout">Logout</a>
                            </li>
                            @if (Context.Session.GetString("Rol") == "Miembro")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="Inicio">Inicio</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="VerPost">Ver Posts</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="VerSolicitudesPendiente">Solicitudes de Amistad</a>
                                </li>
                                                          
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="MostrarMiembros">Agregar Amigos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="RealizarPost">Realizar Post</a>
                                </li>

                            }else if(Context.Session.GetString("Rol")== "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Administrador" asp-action="ListarMiembros">Ver Miembros</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Administrador" asp-action="ListarPublicaciones">Ver Publicaciones</a>
                                </li>
                                
                            }
                        }else{
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="InicioSesion" asp-action="Index">Iniciar Sesión</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Obligatorio2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>