Obligatorio2/Controllers/AdministradorController.cs
using Biblioteca;
using Microsoft.AspNetCore.Mvc;

namespace Obligatorio2.Controllers
{
    public class AdministradorController : Controller
    {

        public IActionResult Index()
        {
            string? rol = HttpContext.Session.GetString("Rol");
            if (rol != null && rol.Equals("Admin"))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index","Error");
            }
            
        }

      

        public IActionResult ListarMiembros()
        {
            string? rol = HttpContext.Session.GetString("Rol");
            if (rol != null && rol.Equals("Admin"))
            {
                try
                {
                    
                    List<Miembro> miembros = Sistema.ObtenerInstancia.MostrarMiembrosParaAdmin();
                    return View(miembros);
                }catch
                {
                    TempData["MensajeError"] = "No hay miembros para mostrar";
                }
                return View();
            }
            else
            {
                TempData["error"] = "No tiene permitido acceder a la página";
                return View("Index","Error");
            }
        }
        public IActionResult BloquearODesbloquear(string Email, string opc)
        {
            string? rol = HttpContext.Session.GetString("Rol");
            if(rol != null && rol.Equals("Admin"))
            {
                try
                {
                    string? user = HttpContext.Session.GetString("usuarioLogueado");
                    
                    if (user != null)
                    {
                        Usuario us = Sistema.ObtenerInstancia.ObtenerMiembroPorEmail(user);
                        Usuario usMiembro = Sistema.ObtenerInstancia.ObtenerMiembroPorEmail(Email);
                        if(us is Administrador && usMiembro is Miembro)
                        {
                            Administrador admin = (Administrador)us;
                            Miembro m = (Miembro)usMiembro;
                            if (opc.Equals("BLOQUEAR"))
                            {
                                admin.Bloquear(m);

                            }
                            else
                            {
                                admin.Desbloquear(m);
                            }

                        }
                    }
                }
                catch
                {

                }
                return RedirectToAction("ListarMiembros");
            }else
            {
                TempData["MensajeError"] = "No tiene permitido acceder a la página";
                return RedirectToAction("Index", "Error");
            }
        }

        public IActionResult ListarPublicaciones()
        {
            string? rol = HttpContext.Session.GetString("Rol");
            if(rol != null && rol.Equals("Admin"))
            {
                List<Post> posts = Sistema.ObtenerInstancia.MostrarPostParaAdmin();
                return View(posts);
            }
            else
            {
                TempData["error"] = "No tiene permitido acceder a la página";
                return RedirectToAction("Index", "Error");
            }
        }

        public IActionResult ListarComentarios(int id)
        {
            string ? rol = HttpContext.Session.GetString("Rol");
            if(rol != null && rol.Equals("Admin"))
            {
                try
                {
                   
                    Post p = Sistema.ObtenerInstancia.ObtenerPostPorId(id);
                    List<Comentario> c = p.Comentarios;
                    ViewBag.Post = p.Titulo;
                    return View(c);
                }
                catch
                {
                    TempData["MensajeError"] = "No hay comentarios en esta publicacion";
                }
                return View();
            }
            else
            {
                TempData["MensajeError"] = "Acceso Denegado";
                return RedirectToAction("Index", "Error");
            }

        }

        public IActionResult BanearPublicaciones(int id, string opc)
        {
            string? rol = HttpContext.Session.GetString("Rol");
            if (rol != null && rol.Equals("Admin"))
            {
                try
                {
                    string? user = HttpContext.Session.GetString("usuarioLogueado");

                    if (user != null)
                    {
                        Usuario us = Sistema.ObtenerInstancia.ObtenerMiembroPorEmail(user);
                        Post p = Sistema.ObtenerInstancia.ObtenerPostPorId(id);
                        if (us is Administrador)
                        {
                            Administrador admin = (Administrador)us;
                            
                            if (opc.Equals("BLOQUEAR"))
                            {
                                admin.Censurar(p);
                                
                            }
                            else
                            {
                                admin.DesCensurar(p);
                            }

                        }
                        return RedirectToAction("ListarPublicaciones");
                    }
                }
                catch
                {

                }
                return RedirectToAction("ListarMiembros");
            }
            else
            {
                TempData["MensajeError"] = "No tiene permitido acceder a la página";
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Obligatorio2/Views/Administrador/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Bienvenido Admin</h1>

@{
}


@if (TempData["MensajeError"] != null)
{

    <div class="alert alert-danger" role="alert">
        @TempData["MensajeError"];
    </div>
}

Obligatorio2/Views/Administrador/ListarComentarios.cshtml
@using Obligatorio2
@using Biblioteca
@model List<Comentario>

<h1>Comentarios del post @ViewBag.Post</h1>
<div class="d-flex justify-content-start">
@foreach(Comentario c in Model)
{
     
                
                
                    <div class="row row-cols-1 row-cols-md-2 g-4 ">
                        
                    <div class="card text-bg-light mb-3 card-body" style="max-width: 18rem;">
                        <div class="card-header">Comentario:</div>
                        <div class="card-body">
                            <h4 class="card-title">@c.Titulo</h4>
                            <p class="card-text">@c.Texto</p>
                    <p>Autor: @c.Autor.Nombre @c.Autor.Apellido</p>
                                <p class="card-text">Like: @c.cantLike()</p>
                                 
                                <p class="card-text">Dislike: @c.cantDisLike()</p>
                                
                        </div>
                    </div>
                    
                    </div>
           
                
                
  

}
</div>

Obligatorio2/Views/Administrador/ListarMiembros.cshtml
@using Obligatorio2
@using Biblioteca
@model List<Miembro>


<h1>Lista de Miembros</h1>
<table class = "table table-striped table-hover">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Apellido
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(Miembro miembros in Model)
        {
            <tr>
                <td>
                    @miembros.Nombre
                </td>
                <td>
                    @miembros.Apellido
                </td>
                @if (miembros.Bloqueado)
                {
                    <td>
                        <a class ="btn btn-primary" href="@Url.Action("BloquearODesbloquear","Administrador", new{Email =@miembros.Email, opc = "DESBLOQUEAR"})">Desbloquear</a>
                    </td>
                }
                else
                {
                    <td>
                        <a class = "btn btn-danger" href="@Url.Action("BloquearODesbloquear","Administrador", new{Email =@miembros.Email, opc = "BLOQUEAR"})">Bloquear</a>
                    </td>
                }
                
                
            </tr>
        }    
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    $(document).ready(function () {
        // Recuperar la posición de desplazamiento desde el almacenamiento local
        var scrollPosition = localStorage.getItem('scrollPosition') || 0;

        // Establecer la posición de desplazamiento al cargar la página
        $(window).scrollTop(scrollPosition);

        // Manejar eventos de recarga para guardar la posición de desplazamiento
        $(window).on('beforeunload', function () {
            localStorage.setItem('scrollPosition', $(window).scrollTop());
        });
    });
</script>

Obligatorio2/Views/Administrador/ListarPublicaciones.cshtml
@using Obligatorio2
@using Biblioteca
@model List<Post>

<h1>Bienvenido a las publicaciones</h1>
<h2>Post</h2>
@foreach(Post posts in Model){
     <div class="card mb-3">
       <figure>
            <img src="@("/Images/" + posts.NombreImagen)" class="card-img-top" alt="Imagen">

        </figure> 
        <div class="card-body">
            <h3 class="card-title">@posts.Titulo</h3>
            <p class="card-text">@posts.Texto</p>
            <p class="card-text"><small class="text-body-secondary">Likes: @posts.like DisLikes: @posts.dislike</small></p>
            <p>Comentarios: @posts.Comentarios.Count() <a class="btn btn-info" href="@Url.Action("ListarComentarios", new {id = posts.Id})">Ver Comentarios</a></p>
            @if (@posts.Baneado)
            {
                <a class="btn btn-success" href="@Url.Action("BanearPublicaciones", new{id = @posts.Id, opc = "DESBLOQUEAR"})">Desbloquear Post</a>
            }
            else
            {
                <a class="btn btn-danger" href="@Url.Action("BanearPublicaciones", new{id = @posts.Id, opc = "BLOQUEAR"})">Bloquear Post</a>
            }
        </div>
        </div>

}

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>


<script>
    $(document).ready(function () {
        // Recuperar la posición de desplazamiento desde el almacenamiento local
        var scrollPosition = localStorage.getItem('scrollPosition') || 0;

        // Establecer la posición de desplazamiento al cargar la página
        $(window).scrollTop(scrollPosition);

        // Manejar eventos de recarga para guardar la posición de desplazamiento
        $(window).on('beforeunload', function () {
            localStorage.setItem('scrollPosition', $(window).scrollTop());
        });
    });
</script>