Obligatorio2/Controllers/InicioSesionController.cs
using Biblioteca;
using Microsoft.AspNetCore.Mvc;

namespace Obligatorio2.Controllers
{
    public class InicioSesionController : Controller
    {
        public IActionResult Index()
        {
            string? us = HttpContext.Session.GetString("usuarioLogueado");
            if (us == null)
            {
                return View();
            }
            else
            {
                TempData["MensajeError"] = "Acceso Denegado";
                return RedirectToAction("Index", "Error");
            }
            
        }
        [HttpPost]
        public IActionResult Login(Usuario s)
        {
            
            try
            {                
                Usuario userLogueado = Sistema.ObtenerInstancia.IniciarSesion(s.Email, s.Contraseña);
                HttpContext.Session.SetString("usuarioLogueado", userLogueado.Email);
                HttpContext.Session.SetString("Rol", userLogueado.Rol);
                HttpContext.Session.SetInt32("Id", userLogueado.Id);

                return RedirectToAction("IdentificarRol");
            } catch (Exception ex)
            {
                TempData["MensajeError"] = ex.Message;
                return RedirectToAction("Index");
            }
        }


        public IActionResult IdentificarRol() 
        {            
            string? rol = HttpContext.Session.GetString("Rol");

                if (rol!= null && rol.Equals("Admin")) 
            {

             return RedirectToAction("Index", "Administrador");

            }else if (rol!= null && rol.Equals("Miembro"))
            {
                return RedirectToAction("Inicio", "Miembro");
            } else
            {
                return RedirectToAction("Index");
            }

        }

    }


  
}

Obligatorio2/Controllers/UsuarioController.cs
using Biblioteca;
using Microsoft.AspNetCore.Mvc;

namespace Obligatorio2.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Inicio()
        {
            string? rol = HttpContext.Session.GetString("Rol");
            if(rol != null && rol.Equals("Miembro"))
            {
                try
                {

                    string? emailLogueado = HttpContext.Session.GetString("usuarioLogueado");
                    if (emailLogueado != null)
                    {
                        Usuario user = Sistema.ObtenerInstancia.ObtenerMiembroPorEmail(emailLogueado);
                        ViewBag.NombreUsuario = user.ToString();
                    }

                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                }
                return View();
            }
            else
            {
                TempData["MensajeError"] = "Error, no puede acceder a la página";
                return RedirectToAction("Index", "Error");
            }
            
            
        }

        
        
        public IActionResult Registrarse()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ValidarRegistro(Miembro m)
        {
            try
            {
                Sistema.ObtenerInstancia.AltaMiembro(m.Email,m.Contraseña,m.Nombre,m.Apellido,m.FechaNacimiento);
                TempData["error"] = false;
                return RedirectToAction("Registrarse");
            } catch (Exception ex)
            {
                TempData["error"] = true;
                TempData["MensajeError"] = ex.Message;
                return RedirectToAction("Registrarse");
            }
           
        }
    }

}

Obligatorio2/Views/InicioSesion/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1>Bienvenido a Social NetWork</h1>
<h2>Inicio Sesión</h2>
<form action="/InicioSesion/Login" method="post">
    <div class="mb-3 row">
        <label for="Email" class="col-sm-2 col-form-label">Ingrese su email</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="Email" name="Email">
        </div>
    </div>
    <div class="mb-3 row">
        <label for="Contraseña" class="col-sm-2 col-form-label">Ingrese su contraseña</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="Contraseña" name="Contraseña">
        </div>
    </div>
    <button type="submit" class="btn btn-primary" >Iniciar Sesion</button>
</form>
<a href="@Url.Action("Registrarse","Usuario")" type="button" class="btn btn-light" id="btnRegistrarse">Registrarse como usuario</a>
@if(TempData["MensajeError"] != null)
{

    <div class="alert alert-danger" role="alert">
        @TempData["MensajeError"];
    </div>
}